// This file is automatically generated by GitHub Actions. Do not edit manually.
const galleryImages = [
    {
        "path": "img/project/007012370937055356303131633.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/0563281547622630123.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/116505606_p0.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/124571319_p0.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/124849486_p0.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/131077864_p0.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/131436827_p0.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/132130444_p0.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/132275568_p0.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/132311115_p0.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20250904-000757.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20250904-000838.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20250904-001022.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20250904-001115.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20250904-001232.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20250904-004132.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20250904-014238.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20250904-014336.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20250904-014510.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231225.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231418.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231505.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231524.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231551.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231615.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231632.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231654.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231712.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231726.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231745.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231802.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231821.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231838.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231854.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231910.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-231943.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-232027.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/20260517-232333.jpg",
        "folder": "project"
    },
    {
        "path": "img/project/23003060604530955.jpg",
        "folder": "project"
    }
];
