// This file is automatically generated by GitHub Actions. Do not edit manually.
const galleryImages = [
    {
        "path": "img/gallery/placeholder1.png",
        "folder": "gallery"
    },
    {
        "path": "img/gallery/placeholder4.gif",
        "folder": "gallery"
    }
];
