import json
from pathlib import Path


IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".svg"}


def is_hidden_path(path):
    return any(part.startswith(".") for part in path.parts)


def generate_gallery_data(base_dir=".", img_dir="img", output_file="gallery_data.js"):
    base_path = Path(base_dir).resolve()
    image_root = base_path / img_dir
    gallery_images = []

    if image_root.exists():
        image_files = sorted(
            (
                path
                for path in image_root.rglob("*")
                if path.is_file()
                and path.suffix.lower() in IMAGE_EXTENSIONS
                and not is_hidden_path(path.relative_to(image_root))
            ),
            key=lambda path: path.relative_to(image_root).as_posix().lower(),
        )

        for image_file in image_files:
            relative_path = image_file.relative_to(image_root)
            folder_path = relative_path.parent.as_posix()
            gallery_images.append(
                {
                    "path": f"{img_dir}/{relative_path.as_posix()}",
                    "folder": "Root" if folder_path == "." else folder_path,
                }
            )
    else:
        print(f"Image directory '{image_root}' was not found. Generating an empty gallery.")

    js_content = (
        "// This file is automatically generated by GitHub Actions. Do not edit manually.\n"
        f"const galleryImages = {json.dumps(gallery_images, indent=4, ensure_ascii=False)};\n"
    )

    output_path = base_path / output_file
    temp_output_path = output_path.with_suffix(f"{output_path.suffix}.tmp")
    temp_output_path.write_text(js_content, encoding="utf-8")
    temp_output_path.replace(output_path)
    print(f"Generated {output_path} with {len(gallery_images)} images.")

if __name__ == "__main__":
    generate_gallery_data()
