name: Generate Gallery Data

on: # Trigger on push to main branch
  push:
    branches:
      - main

jobs:
  generate_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies (if any for script)
      run: | # No specific dependencies for this simple script, but good practice
        python -m pip install --upgrade pip

    - name: Generate gallery_data.js
      run: python generate_gallery_data.py

    - name: Commit and push changes (if any)
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add gallery_data.js
        git diff --staged --quiet || git commit -m "chore: Auto-generate gallery_data.js"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
